version: "3.8"
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: 4tables
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - network
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://root:root@database:5432/4tables?schema=public
    depends_on:
      - database
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - network

networks:
  network:
    driver: bridge
